import re
import hashlib
from urllib.request import urlopen


def get_hash(year, maven_version, suffix):
    url = f"https://frcmaven.wpi.edu/release/edu/wpi/first/thirdparty/frc{year}/opencv/opencv-cpp/{maven_version}/opencv-cpp-{maven_version}-{suffix}.zip.sha256"
    print(f"Getting hash for {url}")

    url_result = urlopen(url)
    sha256 = url_result.read().decode("utf-8")

    return sha256


def get_static_shared_pair(year, maven_version, platform):
    return f"""
    __static_shared_pair(
        mctx,
        name = "{platform}",
        shared_sha256 = "{get_hash(year, maven_version, platform)}",
        static_sha256 = "{get_hash(year, maven_version, platform + 'static')}",
    )
    __static_shared_pair(
        mctx,
        name = "{platform}debug",
        shared_sha256 = "{get_hash(year, maven_version, platform + 'debug')}",
        static_sha256 = "{get_hash(year, maven_version, platform + 'staticdebug')}",
    )"""


def main():
    year = "2025"
    maven_version = "4.10.0-3"
    bzlmod_patch = ".bcr5"

    for filepath in [
        "maven_cpp_deps.bzl",
        "MODULE.bazel",
        "WORKSPACE",
        "libraries/java/opencv/BUILD.bazel",
        "tests/MODULE.bazel",
        "tests/WORKSPACE",
    ]:
        with open(filepath, "r") as f:
            contents = f.read()

        contents = re.sub('YEAR = ".*"', f'YEAR = "{year}"', contents)
        contents = re.sub(
            'MAVEN_VERSION = ".*"', f'MAVEN_VERSION = "{maven_version}"', contents
        )
        contents = re.sub(
            'BZLMOD_PATCH = ".*"', f'BZLMOD_PATCH = "{bzlmod_patch}"', contents
        )

        with open(filepath, "w") as f:
            f.write(contents)

    sha_contents = f"""    maybe(
        http_archive,
        "edu_wpi_opencv-cpp_headers",
        url = "https://frcmaven.wpi.edu/release/edu/wpi/first/thirdparty/frc{year}/opencv/opencv-cpp/{maven_version}/opencv-cpp-{maven_version}-headers.zip",
        sha256 = "{get_hash(year, maven_version, 'headers')}",
        build_file_content = cc_library_headers,
    )
    maybe(
        http_archive,
        "edu_wpi_opencv-cpp_sources",
        url = "https://frcmaven.wpi.edu/release/edu/wpi/first/thirdparty/frc{year}/opencv/opencv-cpp/{maven_version}/opencv-cpp-{maven_version}-sources.zip",
        sha256 = "{get_hash(year, maven_version, 'sources')}",
        build_file_content = cc_library_sources,
    )"""

    for suffix in [
        "linuxathena",
        "linuxsystemcore",
        "linuxarm32",
        "linuxarm64",
        "linuxx86-64",
        "osxarm64",
        "osxuniversal",
        "osxx86-64",
        "windowsx86-64",
        "windowsx86",
        "windowsarm64",
    ]:
        sha_contents += get_static_shared_pair(year, maven_version, suffix)

    new_contents = ""
    with open("maven_cpp_deps.bzl", "r") as f:
        lines = iter(f.readlines())

        # Copy everything up to the autogenerated section
        for line in lines:
            if line.strip() == "# BEGIN static shared pairs":
                break
            new_contents += line

        # Skip everything in the autogenerated section
        for line in lines:
            if line.strip() == "# END static shared pairs":
                break

        # Add our new generated stuff
        new_contents += f"    # BEGIN static shared pairs\n{sha_contents}\n    # END static shared pairs\n"

        # Copy the rest of the file
        for line in lines:
            new_contents += line

    with open("maven_cpp_deps.bzl", "w") as f:
        f.write(new_contents)


if __name__ == "__main__":
    main()
